baseURL = 'https://rtheogh.github.io'
languageCode = 'en-us'
title = 'Reynier Théo'
theme = "quint"
summaryLength = 20                  # Number of characters in your card summaries
pagination.pagerSize = 12

[params]
useToc = true
description = 'Portfolio de Reynier Théo'
contact = "Contact me : [email](mailto:reynier.theo@gmail.com)."

[[menus.main]]
name = 'Linkedin'
url = 'https://www.linkedin.com/in/theo-reynier/'

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/RTheoGH'

[markup.goldmark.renderer]
    unsafe = true

[[params.social]]
    url = "mailto:reynier.theo@gmail.com"
    icon = "/social/email.png"
    name = "Email"

[[params.social]]
    url = "https://github.com/RTheoGH/"
    icon = "/social/github.svg"
    name = "GitHub"